name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # or the branch you want to trigger the action on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push for udagram-api-feed
    - name: Build and push Docker image for subproject1
      uses: docker/build-push-action@v5
      with:
        context: ./udagram-api-feed
        file: ./udagram-api-feed/Dockerfile
        push: true
        tags: thanhduyuit/udagram-api-feed:latest
        
    # Build and push for udagram-api-user
    - name: Build and push Docker image for subproject1
      uses: docker/build-push-action@v5
      with:
        context: ./udagram-api-user
        file: ./udagram-api-user/Dockerfile
        push: true
        tags: thanhduyuit/udagram-api-user:latest
        
    # Build and push for udagram-frontend
    - name: Build and push Docker image for subproject1
      uses: docker/build-push-action@v5
      with:
        context: ./udagram-frontend
        file: ./udagram-frontend/Dockerfile
        push: true
        tags: thanhduyuit/udagram-frontend:latest
        
    # Build and push for udagram-reverseproxy
    - name: Build and push Docker image for subproject1
      uses: docker/build-push-action@v5
      with:
        context: ./udagram-reverseproxy
        file: ./udagram-reverseproxy/Dockerfile
        push: true
        tags: thanhduyuit/udagram-reverseproxy:latest